# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0


apiVersion: {{ .Values.ingress.apiVersion }}
kind: Ingress
metadata:
    name: '{{ .Release.Name }}'
    namespace: '{{ .Values.namespace }}'
    {{- if .Values.ingress.annotations }}
    annotations:
      {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ tpl $value $ | quote }}
      {{- end }}
    {{- end }}
spec:
    ingressClassName: {{ .Values.ingress.ingressClassName }}
    tls:
    - hosts:
      - {{ .Values.domainPrefix }}.{{ .Values.domainName }}
      - {{ .Values.domainPrefix }}-{{ .Values.deploymentEnv }}.{{ .Values.domainName }}
      secretName: "{{ .Release.Name }}-tls"
    rules:
    - host: {{ .Values.domainPrefix }}-{{ .Values.deploymentEnv }}.{{ .Values.domainName }}
      http:
        paths:
        {{ if eq .Values.ingress.apiVersion "networking.k8s.io/v1" }}
        - backend:
            service:
              name: {{ .Release.Name }}
              port:
                number: {{ .Values.servicePort }}
          pathType: Prefix
          path: /
        {{ else }}
        - backend:
            serviceName: {{ .Release.Name }}
            servicePort: {{ .Values.servicePort }}
          path: /
        {{ end }}
