# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0


{{- if  .Values.imageSignatureVerification }}
apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: {{ .Release.Name }}
spec:
  images:
  - glob: "{{ .Values.dockerPreamable }}/{{ .Values.dimage }}@*"
  authorities:
  - name: {{ .Release.Name }}-1
    key:
      data: |
        -----BEGIN PUBLIC KEY-----
        MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEdsiticL9RxsCJhhzfsJ1oaG0LKbH
        b9Bo1IqQUy9OYpxa7nlGrI4yP59jvfHYT2pCQGI4HgJ+SRZn4awAeasbpA==
        -----END PUBLIC KEY-----
{{- end }}
