version: "3"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  docker-compose-up:
    desc: Start all services with docker-compose
    cmds:
      - docker compose --env-file env.config --profile db-only --profile api up

  docker-compose-down:
    desc: Stop all services with docker-compose
    cmds:
      - docker compose --env-file env.config --profile db-only --profile api down

  docker-compose-down-with-volumes:
    desc: Stop all services with docker-compose and remove volumes
    cmds:
      - docker compose --env-file env.config --profile db-only --profile api down -v

  docker-compose-pull-images:
    desc: Update all service images with docker-compose
    cmds:
      - docker compose --env-file env.config --profile db-only --profile api pull