{
 "title": "SRE go helloworld",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Prometheus `/metrics` scrape requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\n  promhttp_metric_handler_requests_total{namespace=\"sre-go-helloworld-dev-blue\"}\n)\n\nby\n\n(kubernetes_pod_name, code)",
     "legendFormat": "Status Code {{code}}"
    }
   ]
  },
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    container_cpu_usage_seconds_total{namespace=\"sre-go-helloworld-dev-blue\"}\n    [5m]\n  )\n)\n\nby (pod, name)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"sre-go-helloworld-dev-blue\"})\n\nby\n\n(name)",
     "legendFormat": "memory: {name=\"{{name}}\"}"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"sre-go-helloworld-dev-blue\"})\n\nby\n\n(name)",
     "legendFormat": "working memory: {name=\"{{name}}\"}"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "HTTP Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    eti_apps_helloworld_http_requests_total{namespace=\"sre-go-helloworld-dev-blue\"}\n    [5m]\n  )\n)\n\nby\n\n(method, route)",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "HTTP Requests Inflight Sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(eti_apps_helloworld_http_requests_in_flight{namespace=\"sre-go-helloworld-dev-blue\"})\n\nby\n\n(route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "HTTP Request Duration Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    eti_apps_helloworld_http_requests_duration_seconds_sum{namespace=\"sre-go-helloworld-dev-blue\"}\n    [5m]\n  )\n)\n\nby\n\n(route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "HTTP Response Size Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    eti_apps_helloworld_http_response_size_bytes_sum{namespace=\"sre-go-helloworld-dev-blue\"}\n    [5m]\n  )\n)\n\nby\n\n(route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Query Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    eti_apps_helloworld_db_queries_total{namespace=\"sre-go-helloworld-dev-blue\"}\n    [5m]\n  )\n)\n\nby\n\n(app)"
    }
   ]
  },
  {
   "title": "Database Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gorm_dbstats_open_connections{namespace=\"sre-go-helloworld-dev-blue\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "gorm_dbstats_in_use{namespace=\"sre-go-helloworld-dev-blue\"}",
     "legendFormat": "In Use"
    },
    {
     "expr": "gorm_dbstats_idle{namespace=\"sre-go-helloworld-dev-blue\"}",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Database Query Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    eti_apps_helloworld_db_queries_duration_seconds_sum{namespace=\"sre-go-helloworld-dev-blue\"}\n    [5m]\n  )\n)\n\nby\n\n(table, method)",
     "legendFormat": "{{method}} \"{{table}}\""
    }
   ]
  },
  {
   "title": "Connection Wait",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(\n  gorm_dbstats_wait_count{namespace=\"sre-go-helloworld-dev-blue\"}\n  [5m]\n)",
     "legendFormat": "Wait Rate"
    },
    {
     "expr": "avg(gorm_dbstats_wait_duration{namespace=\"sre-go-helloworld-dev-blue\"})",
     "legendFormat": "Avg Wait Time"
    }
   ]
  },
  {
   "title": "Connections Closed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gorm_dbstats_max_idle_closed{namespace=\"sre-go-helloworld-dev-blue\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "gorm_dbstats_max_lifetime_closed{namespace=\"sre-go-helloworld-dev-blue\"}",
     "legendFormat": "Lifetime"
    }
   ]
  },
  { "title": "Go", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Process Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=\"sre-go-helloworld-dev-blue\"}",
     "legendFormat": "resident"
    },
    {
     "expr": "process_virtual_memory_bytes{namespace=\"sre-go-helloworld-dev-blue\"}",
     "legendFormat": "virtual"
    }
   ]
  },
  {
   "title": "Process Memory Deriv",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{namespace=\"sre-go-helloworld-dev-blue\"}[5m])",
     "legendFormat": "resident"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes{namespace=\"sre-go-helloworld-dev-blue\"}[5m])",
     "legendFormat": "virtual"
    }
   ]
  },
  {
   "title": "Go Memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{namespace=\"sre-go-helloworld-dev-blue\"}"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{namespace=\"sre-go-helloworld-dev-blue\"}[30s])"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{namespace=\"sre-go-helloworld-dev-blue\"}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\",job=~\"$job\"}",
     "legendFormat": "{{pod}} - heap inuse"
    }
   ]
  },
  {
   "title": "Go Memstats Deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes{namespace=\"sre-go-helloworld-dev-blue\"}[5m])"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{namespace=\"sre-go-helloworld-dev-blue\"}[5m])"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes{namespace=\"sre-go-helloworld-dev-blue\"}[5m])"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\",job=~\"$job\"}[5m])",
     "legendFormat": "{{pod}} - heap inuse"
    }
   ]
  },
  {
   "title": "Open Fds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{namespace=\"sre-go-helloworld-dev-blue\"}"
    }
   ]
  },
  {
   "title": "Open Fds Deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(process_open_fds{namespace=\"sre-go-helloworld-dev-blue\"}[5m])"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{namespace=\"sre-go-helloworld-dev-blue\"}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds_sum{namespace=\"sre-go-helloworld-dev-blue\"}"
    }
   ]
  }
 ]
}