# Default values for configserver-chart.
# This is a YAML-formatted file.
#
# This file provides project specific variables and is joined with another value file
# in MasterDeployments or MinikubeDeployment repos.
#
# When helm is launched it will be done so like this:
#
#  helm template -f <valuesfile> <chartlocation>  > outputfile
#
# and the output will be redirected to a yaml file which will then be manually kubectl applied

# local variables for this deployment can go here

imageSignatureVerification: false
serviceName: sre-go-helloworld
deployment:
  annotations:
    reloader.stakater.com/auto: "true"
  imagePullSecrets:
    - name: regcred
ingress:
  ingressClassName: nginx-internal
  apiVersion: networking.k8s.io/v1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt
domainPrefix: helloworld-go
dbname: helloworlddev
dockerPreamable: 626007623524.dkr.ecr.us-east-2.amazonaws.com/eti-sre
servicePort: "9002"
metricsPort: "9022"

# Pod security Standards
# https://kubernetes.io/docs/concepts/security/pod-security-standards/
# https://snyk.io/blog/10-kubernetes-security-context-settings-you-should-understand/
securityContext:
  allowPrivilegeEscalation: false
  runAsUser: 1001
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: "RuntimeDefault"

# Probes: liveness, readiness and startup
livenessProbe:
  httpGet:
    path: /ping
    port: 9002
  # initialDelaySeconds - Should be set to a duration slightly longer than the application takes to start.
  # If this is set too low, it may restart the pod before the application has a chance to serve traffic.
  initialDelaySeconds: 15
  periodSeconds: 10
  failureThreshold: 1
  successThreshold: 1
  timeoutSeconds: 1

readinessProbe:
  httpGet:
    path: /
    port: 9002
  # initialDelaySeconds - Should be set to a duration slightly longer than the application takes to start.
  # If this is set too low, it may restart the pod before the application has a chance to serve traffic.
  initialDelaySeconds: 15
  periodSeconds: 5
  timeoutSeconds: 1
  failureThreshold: 1
  successThreshold: 1

startupProbe: {}


oidc_client_id: SET_IN_DEPLOYMENT_REPO
oidc_issuer_url: SET_IN_DEPLOYMENT_REPO
configmap: {}
grafana:
  folderName: applications
  ventureName: eti-sre
  appInstance: kube-prometheus-stack
  appName: grafana
  sidecar:
    dashboards:
      label: "grafana_dashboard"

# Environment-specific values
namespace: SET_IN_DEPLOYMENT_REPO       # Overridden in deployment repo for env-specific namespace
tagversion: SET_IN_DEPLOYMENT_REPO      # Defer to deployment repo to capture appropriate version for target environment
dimage: SET_IN_DEPLOYMENT_REPO          # Defer to deployment repo to capture appropriate image name for dev/staging/prod
domainName: SET_IN_DEPLOYMENT_REPO      # Defer to deployment repo to capture appropriate domain name for dev/staging/prod
replicas: 1                             # Default replica count; override in deployment repo for env-specific replica count
deploymentEnv: SET_IN_SRE_CLUSTER_CONFIG_REPO # Defer to sre_cluster_config repo; Value of this param should not impact application
s3_bucket: SET_IN_DEPLOYMENT_REPO       # Defer to deployment repo to capture appropriate s3 bucket name for dev/staging/prod
awsRegionOverride: SET_IN_DEPLOYMENT_REPO   # Defer to deployment repo to capture appropriate aws_region for dev/staging/prod
serviceAccount:
  # Specifies whether a service account should be created
  create: false                         # Override in deployment repo to capture appropriate IAM role arn annotation
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
externalSecrets:                                          # Placeholder/example for specifying secrets retrieval
  secretStoreName: SET_IN_DEPLOYMENT_REPO
  secretStoreKind: SET_IN_DEPLOYMENT_REPO
  data:
  - secretKey: EXAMPLE_PLACEHOLDER
    remoteRef:
      key: EXAMPLE_PLACEHOLDER
      version: "1"
      property: EXAMPLE_PLACEHOLDER
