// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/internal/mgmt/workspaces/{workspaceId}/multi-agentic-systems/{masId}/knowledge-graph": {
            "get": {
                "description": "Returns all nodes and edges in the knowledge graph for the given MAS.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "knowledge-graph"
                ],
                "summary": "Fetch knowledge graph for a MAS",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspaceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Multi-Agentic System ID",
                        "name": "masId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Knowledge graph data",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Workspace or MAS not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/internal/workspaces/{workspaceId}/multi-agentic-systems/{masId}/concepts/similarity-search": {
            "post": {
                "description": "Finds concept nodes nearest to a query embedding vector using HNSW index.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Graph Store"
                ],
                "summary": "Concept similarity search",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspaceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Multi-Agentic System ID",
                        "name": "masId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Include raw embedding vectors in results (debug only)",
                        "name": "include_embeddings",
                        "in": "query"
                    },
                    {
                        "description": "Similarity search request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/app.conceptSimilaritySearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.conceptSimilaritySearchResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Graph not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/internal/workspaces/{workspaceId}/multi-agentic-systems/{masId}/graph/concepts/by_ids": {
            "post": {
                "description": "Returns concept details for each of the provided concept IDs.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Graph Store"
                ],
                "summary": "Fetch concepts by IDs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspaceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Multi-Agentic System ID",
                        "name": "masId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Concept IDs request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/sharedmemory.ConceptsByIdsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/sharedmemory.ConceptsByIdsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/internal/workspaces/{workspaceId}/multi-agentic-systems/{masId}/graph/neighbors/{conceptId}": {
            "get": {
                "description": "Returns the neighboring concepts of a given concept in the knowledge graph.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Graph Store"
                ],
                "summary": "Get neighbors by concept ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspaceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Multi-Agentic System ID",
                        "name": "masId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Concept ID",
                        "name": "conceptId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/sharedmemory.NeighborsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/internal/workspaces/{workspaceId}/multi-agentic-systems/{masId}/graph/paths": {
            "post": {
                "description": "Returns ordered paths through the knowledge graph between a source and target concept.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Graph Store"
                ],
                "summary": "Fetch paths between two concepts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspaceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Multi-Agentic System ID",
                        "name": "masId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Graph paths request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/sharedmemory.GraphPathsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/sharedmemory.GraphPathsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/internal/workspaces/{workspaceId}/multi-agentic-systems/{masId}/shared-memories/rag/similarity-search": {
            "post": {
                "description": "Performs vector similarity search over document embeddings stored for a given workspace and MAS.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Vector Store"
                ],
                "summary": "Search shared memory vectors by similarity",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspaceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Multi-Agentic System ID",
                        "name": "masId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Include raw embedding vectors in results (debug only)",
                        "name": "include_embeddings",
                        "in": "query"
                    },
                    {
                        "description": "Similarity search request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/sharedmemory.VectorSimilaritySearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Search results",
                        "schema": {
                            "$ref": "#/definitions/sharedmemory.VectorSimilaritySearchResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Vector store not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/internal/workspaces/{workspaceId}/multi-agentic-systems/{masId}/shared-memories/vector-store": {
            "post": {
                "description": "Onboards the shared memory vector store for a given MAS. The store is scoped per-MAS.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Vector Store"
                ],
                "summary": "Onboards the shared memory vector store.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspaceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Multi-Agentic System ID",
                        "name": "masId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Onboard vector store request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Vector Store successfully onboarded",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/internal/workspaces/{workspaceId}/shared-memories/vector-store/{store_id}": {
            "delete": {
                "description": "Deletes the shared memory vector store.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Vector Store"
                ],
                "summary": "Deletes the shared memory vector store.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspaceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Store ID",
                        "name": "store_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Delete vector store request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Vector Store successfully deleted",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/workspaces/{workspaceId}/multi-agentic-systems/{masId}/agents/{agentId}/memory-operations": {
            "post": {
                "description": "Forwards REST API requests to a remote memory provider (Mem0, Graphiti, etc.) for agent-specific memory operations.\nThe memory provider base URL and auth credentials are auto-resolved from management plane config based on workspace/MAS/agent IDs.\nThe ` + "`" + `http-url` + "`" + ` field should contain the relative path and query parameters to append to the provider base URL.\n\n**GET example** — retrieve memories:\n` + "`" + `` + "`" + `` + "`" + `json\n{\n\"header\": {},\n\"payload\": {\n\"http-request-type\": \"GET\",\n\"http-url\": \"v1/memories/?user_id=curl-test-user\",\n\"http-request-body\": {},\n\"http-headers\": {}\n}\n}\n` + "`" + `` + "`" + `` + "`" + `\n\n**POST example** — add memories:\n` + "`" + `` + "`" + `` + "`" + `json\n{\n\"header\": {},\n\"payload\": {\n\"http-request-type\": \"POST\",\n\"http-url\": \"/v1/memories/\",\n\"http-request-body\": {\n\"messages\": [{\"role\": \"user\", \"content\": \"I prefer dark mode in all my apps\"}],\n\"user_id\": \"curl-test-user\"\n},\n\"http-headers\": {}\n}\n}\n` + "`" + `` + "`" + `` + "`" + `",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "memory-operations"
                ],
                "summary": "Proxy API requests to a remote memory provider",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspaceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Multi-Agentic System ID",
                        "name": "masId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Agent ID",
                        "name": "agentId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Memory operation request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/memoryoperations.MemoryOperationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Proxied response (actual provider status is in http-status field)",
                        "schema": {
                            "$ref": "#/definitions/memoryoperations.MemoryOperationResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or missing http-request-type",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Memory provider config not found for agent",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "502": {
                        "description": "Failed to forward request to memory provider",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Memory proxy client not configured",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/workspaces/{workspaceId}/multi-agentic-systems/{masId}/semantic-negotiation/decide": {
            "post": {
                "description": "Advances an existing semantic negotiation session with agent replies.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "semantic-negotiation"
                ],
                "summary": "Advance semantic negotiation session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspaceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Multi-Agentic System ID",
                        "name": "masId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Semantic negotiation decide request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/semanticnegotiation.DecideRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Negotiation step executed successfully",
                        "schema": {
                            "$ref": "#/definitions/semanticnegotiation.Response"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Session not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/workspaces/{workspaceId}/multi-agentic-systems/{masId}/semantic-negotiation/start": {
            "post": {
                "description": "Initiates a new semantic negotiation session with multiple agents.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "semantic-negotiation"
                ],
                "summary": "Start semantic negotiation session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspaceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Multi-Agentic System ID",
                        "name": "masId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Semantic negotiation start request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/semanticnegotiation.StartRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Negotiation session started successfully",
                        "schema": {
                            "$ref": "#/definitions/semanticnegotiation.Response"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/workspaces/{workspaceId}/multi-agentic-systems/{masId}/shared-memories": {
            "post": {
                "description": "Creates or updates shared memories with entries (concepts and relations) extracted from the provided trace or OpenClaw output for a given workspace and multi-agentic system.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shared-memories"
                ],
                "summary": "Create or update shared memories.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspaceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Multi-Agentic System ID",
                        "name": "masId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create or update shared memories request",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/sharedmemory.CreateOrUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Shared memories successfully created or updated",
                        "schema": {
                            "$ref": "#/definitions/sharedmemory.CreateOrUpdateResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/workspaces/{workspaceId}/multi-agentic-systems/{masId}/shared-memories/query": {
            "post": {
                "description": "Queries shared memories for a given workspace and multi-agentic system using a graph path query.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shared-memories"
                ],
                "summary": "Fetch shared memories",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspaceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Multi-Agentic System ID",
                        "name": "masId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Query request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/sharedmemory.QueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Query executed successfully",
                        "schema": {
                            "$ref": "#/definitions/sharedmemory.QueryResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app.conceptSimilaritySearchHeader": {
            "type": "object",
            "properties": {
                "agent_id": {
                    "type": "string"
                }
            }
        },
        "app.conceptSimilaritySearchPayload": {
            "type": "object",
            "properties": {
                "embedded_text": {
                    "type": "string"
                },
                "embedding_vector": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "search_metrics": {
                    "type": "string"
                },
                "top_k": {
                    "type": "integer"
                }
            }
        },
        "app.conceptSimilaritySearchRequest": {
            "type": "object",
            "properties": {
                "header": {
                    "$ref": "#/definitions/app.conceptSimilaritySearchHeader"
                },
                "payload": {
                    "$ref": "#/definitions/app.conceptSimilaritySearchPayload"
                },
                "request_id": {
                    "type": "string"
                }
            }
        },
        "app.conceptSimilaritySearchResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "header": {
                    "$ref": "#/definitions/app.conceptSimilaritySearchResponseHeader"
                },
                "response_id": {
                    "type": "string"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/app.conceptSimilaritySearchResult"
                    }
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "app.conceptSimilaritySearchResponseHeader": {
            "type": "object",
            "properties": {
                "agent_id": {
                    "type": "string"
                },
                "mas_id": {
                    "type": "string"
                },
                "workspace_id": {
                    "type": "string"
                }
            }
        },
        "app.conceptSimilaritySearchResult": {
            "type": "object",
            "properties": {
                "concept_id": {
                    "type": "string"
                },
                "concept_name": {
                    "type": "string"
                },
                "embedding_vector": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "score": {
                    "type": "number"
                }
            }
        },
        "cognitionagentclient.ExtractionPayload": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Data contains the extraction payload and its structure depends on Metadata.Format.\n\nSupported formats: \"observe-sdk-otel\" and \"openclaw\n\n1. format = \"observe-sdk-otel\"\n   - Data MUST be a JSON array of ExtractionDataRecord objects.\n   - Example:\n[\n  { TraceId, SpanId, ParentSpanId, SpanName, ServiceName, SpanAttributes, Duration }\n]\n\n2. format = \"openclaw\"\n   - Data is an opaque JSON payload.\n   - The structure is not interpreted or validated by this service and is processed as-is.\n\nClients MUST ensure the Data field matches the structure required by the specified Metadata.Format.",
                    "type": "object"
                },
                "metadata": {
                    "description": "Metadata describes the format and interpretation of the payload.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/cognitionagentclient.ExtractionPayloadMetadata"
                        }
                    ]
                }
            }
        },
        "cognitionagentclient.ExtractionPayloadMetadata": {
            "type": "object",
            "properties": {
                "format": {
                    "description": "Format specifies how the Data field should be interpreted.\n\nSupported values:\n- \"observe-sdk-otel\": Data is a JSON array of ExtractionDataRecord\n- \"openclaw\": Data is an opaque JSON payload",
                    "type": "string"
                }
            }
        },
        "cognitionagents.RequestType": {
            "type": "string",
            "enum": [
                "KNOWLEDGE_VECTORS_UPSERT",
                "KNOWLEDGE_VECTORS_QUERY"
            ],
            "x-enum-varnames": [
                "ReqTypeKnowledgeVectorsUpsert",
                "ReqTypeKnowledgeVectorsQuery"
            ]
        },
        "cognitionagents.SharedMemoryVectorsRequest": {
            "type": "object",
            "properties": {
                "header": {
                    "$ref": "#/definitions/common.Header"
                },
                "request_body": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "request_type": {
                    "$ref": "#/definitions/cognitionagents.RequestType"
                }
            }
        },
        "cognitionagents.SharedMemoryVectorsResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/common.ErrorDetail"
                },
                "header": {
                    "$ref": "#/definitions/common.Header"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "common.ErrorDetail": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "object",
                    "additionalProperties": true
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "common.Header": {
            "type": "object",
            "properties": {
                "agent_id": {
                    "description": "Optional",
                    "type": "string"
                },
                "mas_id": {
                    "description": "Mandatory",
                    "type": "string"
                },
                "workspace_id": {
                    "description": "Mandatory",
                    "type": "string"
                }
            }
        },
        "iocmemoryprovider.KnowledgeVectorMetadataFilter": {
            "type": "object",
            "properties": {
                "chunk_index": {
                    "type": "integer"
                },
                "data_source": {
                    "type": "string"
                },
                "doc_index": {
                    "type": "integer"
                },
                "recorded_at_from": {
                    "type": "string"
                },
                "recorded_at_to": {
                    "type": "string"
                }
            }
        },
        "memoryoperations.MemoryOperationHeader": {
            "type": "object"
        },
        "memoryoperations.MemoryOperationPayload": {
            "type": "object",
            "properties": {
                "http-headers": {
                    "description": "Custom headers",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "http-request-body": {
                    "description": "JSON payload",
                    "type": "object",
                    "additionalProperties": true
                },
                "http-request-type": {
                    "description": "POST, PUT, GET, DELETE, etc.",
                    "type": "string"
                },
                "http-url": {
                    "description": "URL with query parameters (URL encoded)",
                    "type": "string"
                }
            }
        },
        "memoryoperations.MemoryOperationRequest": {
            "type": "object",
            "properties": {
                "header": {
                    "$ref": "#/definitions/memoryoperations.MemoryOperationHeader"
                },
                "payload": {
                    "$ref": "#/definitions/memoryoperations.MemoryOperationPayload"
                }
            }
        },
        "memoryoperations.MemoryOperationResponse": {
            "type": "object",
            "properties": {
                "http-headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "http-response-body": {
                    "type": "object",
                    "additionalProperties": true
                },
                "http-status": {
                    "type": "integer"
                }
            }
        },
        "semanticnegotiation.Agent": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "ID is the unique agent identifier.",
                    "type": "string"
                },
                "name": {
                    "description": "Name is the human-readable agent name.",
                    "type": "string"
                }
            }
        },
        "semanticnegotiation.DecideRequest": {
            "type": "object",
            "properties": {
                "agent_replies": {
                    "description": "AgentReplies are the full SSTPNegotiateMessage objects produced by the\nlocal agent server (/decide) for this round. Each element is a complete\nSSTP envelope as returned by the agent callback server and is forwarded\nverbatim to the negotiation server's /api/semantic-negotiation/negotiate/decide endpoint.",
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        }
                    }
                },
                "session_id": {
                    "description": "SessionID is the session identifier previously provided to the start endpoint.",
                    "type": "string"
                }
            }
        },
        "semanticnegotiation.Response": {
            "type": "object",
            "properties": {
                "envelope": {
                    "description": "Envelope is the full SSTPNegotiateMessage returned by /negotiate/initiate.",
                    "type": "object",
                    "additionalProperties": true
                },
                "final_result": {
                    "description": "FinalResult holds the terminal negotiation envelope when Status is\n\"agreed\", \"broken\", or \"timeout\" (returned by /negotiate/decide).",
                    "type": "object",
                    "additionalProperties": true
                },
                "messages": {
                    "description": "Messages contains the next round's SSTPNegotiateMessage objects when\nStatus is \"ongoing\". Pass these directly to the agent callback server's\nPOST /decide endpoint, then collect replies and send them back via\nthe /semantic-negotiation/decide endpoint.",
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        }
                    }
                },
                "round": {
                    "description": "Round is the SAO round number that was evaluated.",
                    "type": "integer"
                },
                "session_id": {
                    "description": "SessionID echoes the session identifier from the upstream response.",
                    "type": "string"
                },
                "status": {
                    "description": "Status indicates the result of the negotiation step.\nPossible values: \"ongoing\", \"agreed\", \"broken\", \"timeout\".",
                    "type": "string"
                }
            }
        },
        "semanticnegotiation.StartRequest": {
            "type": "object",
            "properties": {
                "agents": {
                    "description": "Agents is the list of participating agents.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/semanticnegotiation.Agent"
                    }
                },
                "content_text": {
                    "description": "ContentText is the negotiation prompt/context used to initialize the session.",
                    "type": "string"
                },
                "n_steps": {
                    "description": "NSteps is the maximum number of negotiation steps.\nIf omitted, defaults to 20.",
                    "type": "integer"
                },
                "session_id": {
                    "description": "SessionID is the client-provided session identifier.\nCurrently assumed globally unique (not scoped by workspace/mas).",
                    "type": "string"
                }
            }
        },
        "sharedmemory.ConceptsByIdsRequest": {
            "type": "object",
            "properties": {
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "sharedmemory.ConceptsByIdsResponse": {
            "type": "object",
            "properties": {
                "concepts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/sharedmemory.GraphConcept"
                    }
                }
            }
        },
        "sharedmemory.CreateOrUpdateRequest": {
            "type": "object",
            "properties": {
                "header": {
                    "description": "Header(s) of the request, optional",
                    "allOf": [
                        {
                            "$ref": "#/definitions/sharedmemory.Header"
                        }
                    ]
                },
                "payload": {
                    "description": "Payload contains the extraction metadata and the raw data to be processed. The structure of the payload data is defined by Payload.Metadata.Format",
                    "allOf": [
                        {
                            "$ref": "#/definitions/cognitionagentclient.ExtractionPayload"
                        }
                    ]
                },
                "request_id": {
                    "description": "ID of the request, optional. If not provided, a random UUID is used to represent the request",
                    "type": "string"
                }
            }
        },
        "sharedmemory.CreateOrUpdateResponse": {
            "type": "object",
            "properties": {
                "graph_store_message": {
                    "description": "Optional message from the graph store upsert operation",
                    "type": "string"
                },
                "response_id": {
                    "description": "ID of the response, this gets populated from request_id",
                    "type": "string"
                },
                "status": {
                    "description": "Status of the request",
                    "type": "string"
                },
                "vector_store_message": {
                    "description": "Optional message from the vector store upsert operation",
                    "type": "string"
                }
            }
        },
        "sharedmemory.GraphConcept": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "sharedmemory.GraphPathsRequest": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "max_depth": {
                    "type": "integer"
                },
                "relations": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "source_id": {
                    "type": "string"
                },
                "target_id": {
                    "type": "string"
                }
            }
        },
        "sharedmemory.GraphPathsResponse": {
            "type": "object",
            "properties": {
                "paths": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/sharedmemory.Path"
                    }
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "sharedmemory.Header": {
            "type": "object",
            "properties": {
                "agent_id": {
                    "description": "ID that represents the agent, optional for query operations",
                    "type": "string"
                }
            }
        },
        "sharedmemory.NeighborsResponse": {
            "type": "object",
            "properties": {
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/sharedmemory.QueryResponseRecord"
                    }
                }
            }
        },
        "sharedmemory.Path": {
            "type": "object",
            "properties": {
                "edges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/sharedmemory.PathEdge"
                    }
                },
                "node_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "path_length": {
                    "type": "integer"
                },
                "symbolic": {
                    "type": "string"
                }
            }
        },
        "sharedmemory.PathEdge": {
            "type": "object",
            "properties": {
                "from_id": {
                    "type": "string"
                },
                "from_name": {
                    "type": "string"
                },
                "relation": {
                    "type": "string"
                },
                "to_id": {
                    "type": "string"
                },
                "to_name": {
                    "type": "string"
                }
            }
        },
        "sharedmemory.QueryConcept": {
            "type": "object",
            "properties": {
                "attributes": {
                    "type": "object",
                    "additionalProperties": true
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "sharedmemory.QueryRelation": {
            "type": "object",
            "properties": {
                "attributes": {
                    "type": "object",
                    "additionalProperties": true
                },
                "id": {
                    "type": "string"
                },
                "node_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "relation": {
                    "type": "string"
                }
            }
        },
        "sharedmemory.QueryRequest": {
            "type": "object",
            "properties": {
                "additional_context": {
                    "description": "AdditionalContext provides optional contextual information to refine query execution. This may include prior conversation state, structured hints, or domain-specific metadata. The contents are treated as opaque by the API and interpreted by downstream components. Each element must be a structured object",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": true
                    }
                },
                "header": {
                    "description": "Header(s) of the request, required (must include agent_id)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/sharedmemory.Header"
                        }
                    ]
                },
                "intent": {
                    "description": "User intent or natural-language query describing what information is being requested. This field is required and is the primary signal used to construct and execute the query",
                    "type": "string"
                },
                "request_id": {
                    "description": "ID of the request, optional. If not provided, a random UUID is used to represent the request",
                    "type": "string"
                },
                "search_strategy": {
                    "description": "Search strategy to be used when executing the query. Currently supported values: \"semantic_graph_traversal\". If not specified, defaults to \"semantic_graph_traversal\"",
                    "type": "string"
                }
            }
        },
        "sharedmemory.QueryResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Message provides detailed information from the query result",
                    "type": "string"
                },
                "response_id": {
                    "description": "ID of the response, this gets populated from request_id",
                    "type": "string"
                }
            }
        },
        "sharedmemory.QueryResponseRecord": {
            "type": "object",
            "properties": {
                "concepts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/sharedmemory.QueryConcept"
                    }
                },
                "relationships": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/sharedmemory.QueryRelation"
                    }
                }
            }
        },
        "sharedmemory.VectorSimilaritySearchPayload": {
            "type": "object",
            "properties": {
                "embedded_text": {
                    "type": "string"
                },
                "embedding_vector": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "filters": {
                    "$ref": "#/definitions/iocmemoryprovider.KnowledgeVectorMetadataFilter"
                },
                "search_metrics": {
                    "type": "string"
                },
                "top_k": {
                    "type": "integer"
                }
            }
        },
        "sharedmemory.VectorSimilaritySearchRequest": {
            "type": "object",
            "properties": {
                "header": {
                    "$ref": "#/definitions/sharedmemory.Header"
                },
                "payload": {
                    "$ref": "#/definitions/sharedmemory.VectorSimilaritySearchPayload"
                },
                "request_id": {
                    "type": "string"
                }
            }
        },
        "sharedmemory.VectorSimilaritySearchResponse": {
            "type": "object",
            "properties": {
                "header": {
                    "$ref": "#/definitions/sharedmemory.Header"
                },
                "request_id": {
                    "type": "string"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/sharedmemory.VectorSimilaritySearchResult"
                    }
                }
            }
        },
        "sharedmemory.VectorSimilaritySearchResult": {
            "type": "object",
            "properties": {
                "chunk_index": {
                    "type": "integer"
                },
                "doc_index": {
                    "type": "integer"
                },
                "domain": {
                    "type": "string"
                },
                "embedded_text": {
                    "type": "string"
                },
                "embedding_vector": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "score": {
                    "type": "number"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "CFN Service API",
	Description:      "IoC Cognition Fabric Node service — shared memory routing and memory operations proxy.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
