// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/cfn/{cfnId}/memory": {
            "post": {
                "description": "Creates a new memory record for a cognition agent",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cognition-agents"
                ],
                "summary": "Create cognition agent memory",
                "parameters": [
                    {
                        "type": "string",
                        "description": "CFN ID",
                        "name": "cfnId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Memory create request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cognitionagents.MemoryCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/cognitionagents.MemoryCreateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cognitionagents.MemoryCreateResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/cognitionagents.MemoryCreateResponse"
                        }
                    }
                }
            }
        },
        "/api/cfn/{cfnId}/memory/concepts/search": {
            "post": {
                "description": "Searches memory concepts for a cognition agent",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cognition-agents"
                ],
                "summary": "Search cognition agent memory concepts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "CFN ID",
                        "name": "cfnId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Concepts search request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cognitionagents.ConceptsSearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cognitionagents.ConceptsSearchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cognitionagents.ConceptsSearchResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/cognitionagents.ConceptsSearchResponse"
                        }
                    }
                }
            }
        },
        "/api/cfn/{cfnId}/memory/paths/search": {
            "post": {
                "description": "Searches for paths between two nodes in cognition agent memory",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cognition-agents"
                ],
                "summary": "Search memory paths",
                "parameters": [
                    {
                        "type": "string",
                        "description": "CFN ID",
                        "name": "cfnId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Paths search request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cognitionagents.PathsSearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cognitionagents.PathsSearchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cognitionagents.PathsSearchResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/cognitionagents.PathsSearchResponse"
                        }
                    }
                }
            }
        },
        "/api/cfn/{cfnId}/memory/search": {
            "post": {
                "description": "Searches cognition agent memory with natural-language queries and embeddings",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cognition-agents"
                ],
                "summary": "Search cognition agent memory",
                "parameters": [
                    {
                        "type": "string",
                        "description": "CFN ID",
                        "name": "cfnId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Memory search request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cognitionagents.MemorySearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cognitionagents.MemorySearchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cognitionagents.MemorySearchResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/cognitionagents.MemorySearchResponse"
                        }
                    }
                }
            }
        },
        "/api/internal/audit-events": {
            "get": {
                "description": "Returns audit events with optional resource_type and audit_type query filters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "audit"
                ],
                "summary": "List audit events",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by resource type",
                        "name": "resource_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by audit type",
                        "name": "audit_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/audit.Audit"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new audit event after validating required fields and enum values",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "audit"
                ],
                "summary": "Create an audit event",
                "parameters": [
                    {
                        "description": "Audit event request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/audit.CreateAuditEventRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/internal/audit-events/{eventId}": {
            "get": {
                "description": "Returns a single audit event by its UUID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "audit"
                ],
                "summary": "Get an audit event by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Audit event UUID",
                        "name": "eventId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/audit.Audit"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a single audit event by its UUID (internal API only)",
                "tags": [
                    "audit"
                ],
                "summary": "Delete an audit event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Audit event UUID",
                        "name": "eventId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/cfn/dummy": {
            "get": {
                "description": "Returns mock CFN data",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cfn"
                ],
                "summary": "Get CFN dummy data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    }
                }
            }
        },
        "/api/workspaces/{workspaceId}/multi-agentic-systems/{masId}/agents/{agentId}/memory-operations": {
            "post": {
                "description": "Forwards HTTP requests to a remote memory provider (Mem0, Graphiti, etc.) for agent-specific memory operations.\nThe memory provider base URL and auth credentials are auto-resolved from management plane config based on workspace/MAS/agent IDs.\nThe ` + "`" + `http-url` + "`" + ` field should contain the relative path and query parameters to append to the provider base URL.\n\n**GET example** — retrieve memories:\n` + "`" + `` + "`" + `` + "`" + `json\n{\n\"header\": {},\n\"payload\": {\n\"http-request-type\": \"GET\",\n\"http-url\": \"v1/memories/?user_id=curl-test-user\",\n\"http-request-body\": {},\n\"http-headers\": {}\n}\n}\n` + "`" + `` + "`" + `` + "`" + `\n\n**POST example** — add memories:\n` + "`" + `` + "`" + `` + "`" + `json\n{\n\"header\": {},\n\"payload\": {\n\"http-request-type\": \"POST\",\n\"http-url\": \"/v1/memories/\",\n\"http-request-body\": {\n\"messages\": [{\"role\": \"user\", \"content\": \"I prefer dark mode in all my apps\"}],\n\"user_id\": \"curl-test-user\"\n},\n\"http-headers\": {}\n}\n}\n` + "`" + `` + "`" + `` + "`" + `",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "memory-operations"
                ],
                "summary": "Proxy HTTP requests to a remote memory provider",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspaceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Multi-Agentic System ID",
                        "name": "masId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Agent ID",
                        "name": "agentId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Memory operation request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/memoryoperations.MemoryOperationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Proxied response (actual provider status is in http-status field)",
                        "schema": {
                            "$ref": "#/definitions/memoryoperations.MemoryOperationResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or missing http-request-type",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Memory provider config not found for agent",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "502": {
                        "description": "Failed to forward request to memory provider",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Memory proxy client not configured",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/workspaces/{workspaceId}/multi-agentic-systems/{masId}/shared-memories": {
            "post": {
                "description": "Upserts shared memory entries (concepts and relations) for a given workspace and multi-agentic system.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shared-memories"
                ],
                "summary": "Upsert shared memories.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspaceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Multi-Agentic System ID",
                        "name": "masId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Upsert request",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/iocmemoryprovider.KnowledgeGraphStoreRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Shared memories successfully upserted",
                        "schema": {
                            "$ref": "#/definitions/iocmemoryprovider.KnowledgeGraphStoreResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/workspaces/{workspaceId}/multi-agentic-systems/{masId}/shared-memories/query": {
            "post": {
                "description": "Queries shared memories for a given workspace and multi-agentic system using a graph path query.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shared-memories"
                ],
                "summary": "Fetch shared memories",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspaceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Multi-Agentic System ID",
                        "name": "masId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Query request",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/iocmemoryprovider.KnowledgeGraphQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Query executed successfully",
                        "schema": {
                            "$ref": "#/definitions/iocmemoryprovider.KnowledgeGraphQueryResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "audit.Audit": {
            "type": "object",
            "properties": {
                "audit_extra_information": {
                    "type": "string"
                },
                "audit_information": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "audit_resource_identifier": {
                    "type": "string"
                },
                "audit_type": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "created_on": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_modified_by": {
                    "type": "string"
                },
                "last_modified_on": {
                    "type": "string"
                },
                "operation_id": {
                    "type": "string"
                },
                "resource_identifier": {
                    "type": "string"
                },
                "resource_type": {
                    "type": "string"
                }
            }
        },
        "audit.CreateAuditEventRequest": {
            "type": "object",
            "properties": {
                "audit_extra_information": {
                    "type": "string"
                },
                "audit_information": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "audit_resource_identifier": {
                    "type": "string"
                },
                "audit_type": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "last_modified_by": {
                    "type": "string"
                },
                "operation_id": {
                    "type": "string"
                },
                "resource_identifier": {
                    "type": "string"
                },
                "resource_type": {
                    "type": "string"
                }
            }
        },
        "cognitionagents.ConceptsSearchRequest": {
            "type": "object",
            "properties": {
                "header": {
                    "$ref": "#/definitions/cognitionagents.Header"
                }
            }
        },
        "cognitionagents.ConceptsSearchResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/cognitionagents.ErrorDetail"
                },
                "header": {
                    "$ref": "#/definitions/cognitionagents.Header"
                },
                "response_id": {
                    "type": "string"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": true
                    }
                }
            }
        },
        "cognitionagents.ErrorDetail": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "object",
                    "additionalProperties": true
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "cognitionagents.Header": {
            "type": "object",
            "properties": {
                "agent_id": {
                    "description": "Optional",
                    "type": "string"
                },
                "mas_id": {
                    "description": "Mandatory",
                    "type": "string"
                },
                "workspace_id": {
                    "description": "Mandatory",
                    "type": "string"
                }
            }
        },
        "cognitionagents.MemoryCreateRequest": {
            "type": "object",
            "properties": {
                "header": {
                    "$ref": "#/definitions/cognitionagents.Header"
                }
            }
        },
        "cognitionagents.MemoryCreateResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/cognitionagents.ErrorDetail"
                },
                "header": {
                    "$ref": "#/definitions/cognitionagents.Header"
                },
                "response_id": {
                    "type": "string"
                }
            }
        },
        "cognitionagents.MemorySearchRequest": {
            "type": "object",
            "properties": {
                "embeding": {
                    "description": "Kept as \"embeding\" per API spec",
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "header": {
                    "$ref": "#/definitions/cognitionagents.Header"
                },
                "k": {
                    "type": "integer"
                },
                "queries": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "cognitionagents.MemorySearchResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/cognitionagents.ErrorDetail"
                },
                "header": {
                    "$ref": "#/definitions/cognitionagents.Header"
                },
                "response_id": {
                    "type": "string"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/cognitionagents.QueryResult"
                    }
                }
            }
        },
        "cognitionagents.PathEdge": {
            "type": "object",
            "properties": {
                "from_id": {
                    "type": "string"
                },
                "from_name": {
                    "type": "string"
                },
                "relation": {
                    "type": "string"
                },
                "to_id": {
                    "type": "string"
                },
                "to_name": {
                    "type": "string"
                }
            }
        },
        "cognitionagents.PathResult": {
            "type": "object",
            "properties": {
                "edges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/cognitionagents.PathEdge"
                    }
                },
                "node_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "path_length": {
                    "type": "integer"
                },
                "symbolic": {
                    "type": "string"
                }
            }
        },
        "cognitionagents.PathsSearchPayload": {
            "type": "object",
            "properties": {
                "from_id": {
                    "type": "string"
                },
                "max_depth": {
                    "type": "integer"
                },
                "relations": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "to_id": {
                    "type": "string"
                }
            }
        },
        "cognitionagents.PathsSearchRequest": {
            "type": "object",
            "properties": {
                "header": {
                    "$ref": "#/definitions/cognitionagents.Header"
                },
                "payload": {
                    "$ref": "#/definitions/cognitionagents.PathsSearchPayload"
                }
            }
        },
        "cognitionagents.PathsSearchResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/cognitionagents.ErrorDetail"
                },
                "header": {
                    "$ref": "#/definitions/cognitionagents.Header"
                },
                "paths": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/cognitionagents.PathResult"
                    }
                },
                "response_id": {
                    "type": "string"
                }
            }
        },
        "cognitionagents.QueryResult": {
            "type": "object",
            "properties": {
                "hits": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": true
                    }
                },
                "query": {
                    "type": "string"
                }
            }
        },
        "iocmemoryprovider.Concept": {
            "type": "object",
            "properties": {
                "attributes": {
                    "type": "object",
                    "additionalProperties": true
                },
                "description": {
                    "type": "string"
                },
                "embeddings": {
                    "$ref": "#/definitions/iocmemoryprovider.EmbeddingConfig"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "iocmemoryprovider.ConceptRecord": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "iocmemoryprovider.EmbeddingConfig": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "iocmemoryprovider.KnowledgeGraphQueryCriteria": {
            "type": "object",
            "properties": {
                "depth": {
                    "type": "integer"
                },
                "query_type": {
                    "type": "string"
                },
                "use_direction": {
                    "type": "boolean"
                }
            }
        },
        "iocmemoryprovider.KnowledgeGraphQueryRequest": {
            "type": "object",
            "properties": {
                "mas_id": {
                    "type": "string"
                },
                "memory_type": {
                    "type": "string"
                },
                "query_criteria": {
                    "$ref": "#/definitions/iocmemoryprovider.KnowledgeGraphQueryCriteria"
                },
                "records": {
                    "$ref": "#/definitions/iocmemoryprovider.QueryRecords"
                },
                "request_id": {
                    "type": "string"
                },
                "wksp_id": {
                    "type": "string"
                }
            }
        },
        "iocmemoryprovider.KnowledgeGraphQueryResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/iocmemoryprovider.KnowledgeGraphQueryResponseRecord"
                    }
                },
                "request_id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/iocmemoryprovider.ResponseStatus"
                }
            }
        },
        "iocmemoryprovider.KnowledgeGraphQueryResponseRecord": {
            "type": "object",
            "properties": {
                "concepts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/iocmemoryprovider.Concept"
                    }
                },
                "relationships": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/iocmemoryprovider.Relation"
                    }
                }
            }
        },
        "iocmemoryprovider.KnowledgeGraphStoreRequest": {
            "type": "object",
            "properties": {
                "force_replace": {
                    "type": "boolean"
                },
                "mas_id": {
                    "type": "string"
                },
                "memory_type": {
                    "type": "string"
                },
                "records": {
                    "$ref": "#/definitions/iocmemoryprovider.Records"
                },
                "request_id": {
                    "type": "string"
                },
                "wksp_id": {
                    "type": "string"
                }
            }
        },
        "iocmemoryprovider.KnowledgeGraphStoreResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/iocmemoryprovider.ResponseStatus"
                }
            }
        },
        "iocmemoryprovider.QueryRecords": {
            "type": "object",
            "properties": {
                "concepts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/iocmemoryprovider.ConceptRecord"
                    }
                }
            }
        },
        "iocmemoryprovider.Records": {
            "type": "object",
            "properties": {
                "concepts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/iocmemoryprovider.Concept"
                    }
                },
                "relations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/iocmemoryprovider.Relation"
                    }
                }
            }
        },
        "iocmemoryprovider.Relation": {
            "type": "object",
            "properties": {
                "attributes": {
                    "type": "object",
                    "additionalProperties": true
                },
                "embeddings": {
                    "$ref": "#/definitions/iocmemoryprovider.EmbeddingConfig"
                },
                "id": {
                    "type": "string"
                },
                "node_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "relation": {
                    "type": "string"
                }
            }
        },
        "iocmemoryprovider.ResponseStatus": {
            "type": "string",
            "enum": [
                "success",
                "failure",
                "validation error",
                "not found"
            ],
            "x-enum-varnames": [
                "ResponseStatusSuccess",
                "ResponseStatusFailure",
                "ResponseStatusValidationError",
                "ResponseStatusNotFound"
            ]
        },
        "memoryoperations.MemoryOperationHeader": {
            "type": "object"
        },
        "memoryoperations.MemoryOperationPayload": {
            "type": "object",
            "properties": {
                "http-headers": {
                    "description": "Custom headers",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "http-request-body": {
                    "description": "JSON payload",
                    "type": "object",
                    "additionalProperties": true
                },
                "http-request-type": {
                    "description": "POST, PUT, GET, DELETE, etc.",
                    "type": "string"
                },
                "http-url": {
                    "description": "URL with query parameters (URL encoded)",
                    "type": "string"
                }
            }
        },
        "memoryoperations.MemoryOperationRequest": {
            "type": "object",
            "properties": {
                "header": {
                    "$ref": "#/definitions/memoryoperations.MemoryOperationHeader"
                },
                "payload": {
                    "$ref": "#/definitions/memoryoperations.MemoryOperationPayload"
                }
            }
        },
        "memoryoperations.MemoryOperationResponse": {
            "type": "object",
            "properties": {
                "http-headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "http-response-body": {
                    "type": "object",
                    "additionalProperties": true
                },
                "http-status": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "CFN Service API",
	Description:      "IoC Cognitive Fabric Node service — shared memory routing, memory operations proxy, and audit trail.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
