// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/internal/audit-events": {
            "get": {
                "description": "Returns audit events with optional resource_type and audit_type query filters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "audit"
                ],
                "summary": "List audit events",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by resource type",
                        "name": "resource_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by audit type",
                        "name": "audit_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/audit.Audit"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new audit event after validating required fields and enum values",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "audit"
                ],
                "summary": "Create an audit event",
                "parameters": [
                    {
                        "description": "Audit event request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/audit.CreateAuditEventRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/internal/audit-events/{eventId}": {
            "get": {
                "description": "Returns a single audit event by its UUID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "audit"
                ],
                "summary": "Get an audit event by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Audit event UUID",
                        "name": "eventId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/audit.Audit"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a single audit event by its UUID (internal API only)",
                "tags": [
                    "audit"
                ],
                "summary": "Delete an audit event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Audit event UUID",
                        "name": "eventId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/cfn/dummy": {
            "get": {
                "description": "Returns mock CFN data",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cfn"
                ],
                "summary": "Get CFN dummy data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    }
                }
            }
        },
        "/api/workspaces/{workspaceId}/multi-agentic-systems/{systemId}/shared-memories": {
            "post": {
                "description": "Upserts shared memory entries for a given workspace and multi-agentic system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shared-memories"
                ],
                "summary": "Upsert shared memories",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspaceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Multi-Agentic System ID",
                        "name": "systemId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Upsert request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/sharedmemory.SharedMemoryUpsertRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/sharedmemory.SharedMemoryUpsertResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/workspaces/{workspaceId}/multi-agentic-systems/{systemId}/shared-memories/query": {
            "post": {
                "description": "Fetches shared memory entries for a given workspace and multi-agentic system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shared-memories"
                ],
                "summary": "Fetch shared memories",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspaceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Multi-Agentic System ID",
                        "name": "systemId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Query request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/sharedmemory.SharedMemoryQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/sharedmemory.SharedMemoryQueryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "audit.Audit": {
            "type": "object",
            "properties": {
                "audit_extra_information": {
                    "type": "string"
                },
                "audit_information": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "audit_resource_identifier": {
                    "type": "string"
                },
                "audit_type": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "created_on": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_modified_by": {
                    "type": "string"
                },
                "last_modified_on": {
                    "type": "string"
                },
                "operation_id": {
                    "type": "string"
                },
                "resource_identifier": {
                    "type": "string"
                },
                "resource_type": {
                    "type": "string"
                }
            }
        },
        "audit.CreateAuditEventRequest": {
            "type": "object",
            "properties": {
                "audit_extra_information": {
                    "type": "string"
                },
                "audit_information": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "audit_resource_identifier": {
                    "type": "string"
                },
                "audit_type": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "last_modified_by": {
                    "type": "string"
                },
                "operation_id": {
                    "type": "string"
                },
                "resource_identifier": {
                    "type": "string"
                },
                "resource_type": {
                    "type": "string"
                }
            }
        },
        "sharedmemory.SharedMemoryQueryRequest": {
            "type": "object"
        },
        "sharedmemory.SharedMemoryQueryResponse": {
            "type": "object"
        },
        "sharedmemory.SharedMemoryUpsertRequest": {
            "type": "object",
            "properties": {
                "memories": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": {}
                    }
                },
                "relationships": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": {}
                    }
                }
            }
        },
        "sharedmemory.SharedMemoryUpsertResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Template API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
