##############################################
# Corona & Blackduck Scan using Shared Action
##############################################
name: Call Corona & Blackduck Scan Shared Action

on: 
  workflow_dispatch:

jobs:
#  call_corona_bd_scan_job:
#    runs-on: ${{ vars.UBUNTU_RUNNER }}
#    name: Corona and blackduck Scan
#    steps:
#      - name: Import Vault Secrets
#        uses: hashicorp/vault-action@v2.7.5
#        with:
#          url:  ${{ vars.KEEPER_URL }}
#          method: approle
#          roleId: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
#          secretId: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
#          namespace: ${{ vars.VAULT_NAMESPACE }}
#          secrets: |
#              ${{ vars.VAULT_SECRET_PATH }}  GHCR_USERNAME                  | GHCR_USERNAME ;
#              ${{ vars.VAULT_SECRET_PATH }}  GHCR_TOKEN                     | GHCR_TOKEN ;
#              ${{ vars.VAULT_SECRET_PATH }}  CORONA_HOST                    | CORONA_HOST ;
#              ${{ vars.VAULT_SECRET_PATH }}  CORONA_API_GW_CLIENT_HOST      | CORONA_API_GW_CLIENT_HOST ;
#              ${{ vars.VAULT_SECRET_PATH }}  CORONA_USERNAME                | CORONA_USERNAME ;
#              ${{ vars.VAULT_SECRET_PATH }}  CORONA_PAT                     | CORONA_PAT ;
#              ${{ vars.VAULT_SECRET_PATH }}  CORONA_API_GW_CLIENT_ID        | CORONA_API_GW_CLIENT_ID ;
#              ${{ vars.VAULT_SECRET_PATH }}  CORONA_API_GW_CLIENT_SECRET    | CORONA_API_GW_CLIENT_SECRET ;
#              ${{ vars.VAULT_SECRET_PATH }}  ARTIFACTORY_ENCRYPTED_PASSWORD | ARTIFACTORY_ENCRYPTED_PASSWORD
#
#      - name: Corona & Blackduck Shared Action
#        uses: cisco-eti/gh-shared-actions/corona/corona-bd-scan@debian-image
#        with:
#          enable-corona: true
#          enable-bd: false
#          ghcr-username: ${{ env.GHCR_USERNAME }}
#          ghcr-token: ${{ env.GHCR_TOKEN }}
#          corona-host: ${{ env.CORONA_HOST }}
#          api-gh-client-host: ${{ env.CORONA_API_GW_CLIENT_HOST }}
#          api-gh-client-id: ${{ env.CORONA_API_GW_CLIENT_ID }}
#          api-gh-client-secret: ${{ env.CORONA_API_GW_CLIENT_SECRET }}
#          corona-username: ${{ env.CORONA_USERNAME }}
#          corona-password: ${{ env.CORONA_PAT }}
#          corona-product-name: ${{ vars.CORONA_PRODUCT_NAME }}
#          corona-product-id: ${{ vars.CORONA_PRODUCT_ID }}
#          corona-release-id: ${{ vars.CORONA_RELEASE_ID }}
#          corona-csdl-id: ${{ vars.CORONA_CSDL_ID }}
#          corona-security-contact: ${{ vars.CORONA_SECURITY_CONTACT }}
#          corona-engineering-contact: ${{ vars.CORONA_ENGINEERING_CONTACT }}
#          corona-image-admins: ${{ vars.CORONA_IMAGE_ADMINS }}
#          dbhub-artifactory-token: ${{ env.ARTIFACTORY_ENCRYPTED_PASSWORD }}
#          ghcr-org-registry: "ghcr.io/cisco-eti"
#          image-name: "${{ github.event.repository.name }}"
#          image-tag: "2024.11.13-ea39446-189"
#          language: "go"
